344 advancement method 1   standard
patrickmohrmann/earthdawn4eV2 pull request #1115
Opened 2024-11-06 23:16 UTC by patrickmohrmann

2024-11-08 14:33 UTC, ChristopherSD requested changes

2024-11-08 15:18 UTC, patrickmohrmann commented on module/data/actor/pc.mjs
> +    console.log( "newActor", newActor );
done

2024-11-08 15:18 UTC, patrickmohrmann commented on module/data/actor/pc.mjs
> +    const disciplineAfterCreation = newActor.items.filter( item => item.type === "discipline" )[0];
great, did it.

2024-11-16 21:19 UTC, ChristopherSD approved these changes

2024-11-16 21:19 UTC, merged