Patrick dev 02
patrickmohrmann/earthdawn4eV2 pull request #128
Opened 2023-10-04 19:31 UTC by patrickmohrmann

test

2023-10-06 18:30 UTC, ChristopherSD requested changes
See comments in files.

2023-10-06 18:30 UTC, ChristopherSD commented on module/sheets/actor-sheet.mjs
This needs to be arranged in the ES6 module directory structure. Do you want to do this together or should I do it separately and make an extra pull request for that?

Line 20: No trailing comma, please remove.

2023-10-06 18:30 UTC, ChristopherSD commented on module/sheets/item-sheet.mjs
This needs to be arranged in the ES6 module directory structure. Do you want to do this together or should I do it separately and make an extra pull request for that?

2023-10-06 18:30 UTC, ChristopherSD commented on earthdawn4e.mjs
The imports need to be arranged in the ES6 module directory structure. Do you want to do this together or should I do it separately and make an extra pull request for that?

Line 53: The function should not return anything, since the Promise of the `preloadHandlebarsTemplates` is ignored anyways.

2023-10-06 18:30 UTC, ChristopherSD commented on module/helpers/handlebar-helpers.js
This needs to be arranged in the ES6 module directory structure. Do you want to do this together or should I do it separately and make an extra pull request for that?

The file should have the `*.mjs` extension.

This can be consolidated into a `utils.mjs` file.

2023-10-06 18:30 UTC, ChristopherSD commented on module/helpers/templates.mjs
This needs to be arranged in the ES6 module directory structure. Do you want to do this together or should I do it separately and make an extra pull request for that?

This can be consolidated into a `utils.mjs` file.

The `loadTemplates` function also allows for object of templates as a parameter. This way you do not need to write the entire file name when using a partial in an hbs-file, but rather can use the shorter key. Here is a code snippet that creates the object automatically:
```javascript
const partials = [
    "systems/ed4e/templates/actor/character-partials/header-section.hbs",
    ...
]

const paths = {};
  for ( const path of partials ) {
    paths[path.replace(".hbs", ".html")] = path;
    paths[`ed4e.${path.split("/").pop().replace(".hbs", "")}`] = path;
  }

  return loadTemplates(paths);
```

2023-10-06 19:57 UTC, patrickmohrmann commented on earthdawn4e.mjs
fine if you do it, I can figure it out in the pull request

2023-10-07 20:11 UTC, patrickmohrmann reviewed
update

2023-10-07 20:11 UTC, patrickmohrmann commented on module/sheets/actor-sheet.mjs
will be handled in future pull

2023-10-07 20:11 UTC, patrickmohrmann commented on module/sheets/item-sheet.mjs
will be handled in future pull

2023-10-07 20:19 UTC, ChristopherSD approved these changes

2023-10-07 20:19 UTC, merged